### PR TITLE
Fixed random crash when accessing readableMap

### PR DESCRIPTION
**Pull request by abrel**
Safer access to Facebook readableMap object

### CODE REVIEW

**Comment by uerceg** [comment]
Hi @abrel 

Thanks for the PR. Can you give us use case in which you were seeing crashes?

**Comment by gmeluski** [comment]
I have one, using `react-native-adjust` version 4.12.3:

```
export function initAdjust() {
  let adjustEnv;
  if (Device.defaultEnv === 'production') {
    adjustEnv = AdjustConfig.EnvironmentProduction;
  } else {
    adjustEnv = AdjustConfig.EnvironmentSandbox;
  }
  const adjustConfig = new AdjustConfig(ADJUST_APP_TOKEN, adjustEnv);

  Adjust.getAttribution(() => {
    Adjust.getAdid(() => adjustReady.resolve(getAdjustId));
  });
  Adjust.create(adjustConfig);
}

```

It's difficult to determine if there is a relationship between actions that take place in the app and our methods that use `Adjust.trackEvent()`, or whether this is firing on the initialization that takes place above.

This is the resulting error.
```
com.facebook.react.bridge.NoSuchKeyException: secretId
    at com.facebook.react.bridge.ReadableNativeMap.isNull(ReadableNativeMap.java:115)
    at com.adjust.nativemodule.Adjust.create(Adjust.java:192)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:761)
```

Rolling back to 4.11.7 lets Android builds work as expected for our team.

**Comment by uerceg** [comment]
Thanks for the PR and explanation, will be included hopefully in our next React Native update.

**Comment by uerceg** [comment]
One more time, thanks for the PR. Replaced with https://github.com/adjust/react_native_sdk/pull/43.

Cheers!

**Pull request closed without merging**
